[package]
name = "rpdidrums"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13.4"
crossbeam-channel = "0.5.0"
rand = "0.8.4"
hound = "3.4.0"
